### ISSUE TITLE
select another timestamp key

### ISSUE THREAD

**Issue by yanzixiang** [datalust/seq-input-gelf#112]
i use [gelflib](https://github.com/serge-14/gelflib) send the log from systemd-journald to seq-input-gelf

the systemd-journal use this entry
[__REALTIME_TIMESTAMP](https://www.man7.org/linux/man-pages/man7/systemd.journal-fields.7.html)
it is in **microseconds** since the epoch UTC,
but gelflib's setTime [setTime ](https://github.com/serge-14/gelflib/blob/3ae18851b2182eb2952fe3f52f3ae3f41b80d2ac/include/MessageBuilder.hpp#L113) function
just use time_t which is in **s**

so my log shown in seq events are like this
![image](https://user-images.githubusercontent.com/33214/195485812-f2e80af1-c50a-48cd-b429-19d2f3655759.png)

after i change the timestamp key in gelflib to a double value,
my log shown in seq events are like this
![image](https://user-images.githubusercontent.com/33214/195485994-f236e47c-c8c3-4695-9e45-8410e38b62d9.png)
and cause seq-input-gelf stop to run
![image](https://user-images.githubusercontent.com/33214/195486192-d400a593-23ee-4e7e-88b3-935651d3327c.png)

so i want to send to ms_timestamp to another key,
and select that key as defalut timestamp column.

**Comment by KodrAus** [comment]
Sorry for the slow reply here @yanzixiang!

GELF requires the timestamp to be seconds since the epoch, with millisecond precision following a decimal point. It looks like maybe you're ending up with that microseconds-since-epoch value in your GELF message, which is then overflowing in this server because it's trying to treat them as seconds.

We definitely shouldn't ever panic on any input, so I've opened #113 to not overflow when encountering very large timestamp values.

This library doesn't do a lot of transformation itself, but one option you could consider if you want more control over how those journald events are emitted is using a log processing pipeline like Fluent Bit, which has a [Systemd input](https://docs.fluentbit.io/manual/pipeline/inputs/systemd), and can [output directly to Seq with very little configuration](https://blog.datalust.co/tailing-a-log-file-or-folder-with-fluent-bit-and-seq/).

**Comment by yanzixiang** [comment]
> GELF requires the timestamp to be seconds since the epoch, with millisecond precision following a decimal point. It looks like maybe you're ending up with that microseconds-since-epoch value in your GELF message, which is then overflowing in this server because it's trying to treat them as seconds.

so, the timestamp should be string "1665628250.123" ?
i have try this string, but it fails too...


> This library doesn't do a lot of transformation itself, but one option you could consider if you want more control over how those journald events are emitted is using a log processing pipeline like Fluent Bit, which has a [Systemd input](https://docs.fluentbit.io/manual/pipeline/inputs/systemd), and can [output directly to Seq with very little configuration](https://blog.datalust.co/tailing-a-log-file-or-folder-with-fluent-bit-and-seq/).

my device and the seq server is not always connected,
i want to *sync* all systemd's log entrys to seq,
so i thinks i can NOT use Fluent Bit to do this.

**Comment by KodrAus** [comment]
Just coming back through some triage here. We're going to keep this library focused on the GELF format as specified. In order for events to be ingested correctly, they need to be compliant with the GELF spec and use its seconds since the epoch format.

Thanks again for the original report.
